version: '3.9'

services:
  issue-db:
    container_name: issue-db
    image: mongo
    networks: 
      - default
    ports: 
      - "27017:27017"
    volumes: 
      - mongodbdata:/data/db

  issue-service:
    container_name: issue-service
    build:
      context: .
      dockerfile: Issue-Service/Dockerfile
    ports:
      - 5001:80
    networks:
      - default
    environment:
      ASPNETCORE_ENVIRONMENT: Staging

networks:
  default:
    name: swsp

volumes:
  mongodbdata: